version: "2"
linters:
  default: fast
  enable:
    - errcheck
    - gosec
    - revive
  disable:
    - copyloopvar
    - cyclop
    - depguard
    - dupl
    - funlen
    - gocognit
    - goconst
    - gocyclo
    - lll
    - maintidx
    - mnd
    - nestif
    - nlreturn
    - testpackage
    - wsl
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
